apiVersion: v1
kind: Service
metadata:
  name: lamport-ui
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamport-ui
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: nicholasjackson/lamport-ui:v0.1.2
        ports:
        - containerPort: 5173